site_name: Harus Docs
site_url: https://docs.azusachino.icu
site_description: Palette gives you the ability, but you're the possibility.
theme:
  # custom_dir: overrides
  icon:
    repo: fontawesome/brands/github
  name: material
  features:
    - content.action.edit
    - content.code.copy
    - navigation.expand
    - navigation.footer
    - navigation.indexes 
    # conflict with mkdocs-static-i18n
    # - navigation.instant
    - navigation.sections
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
extra:
  analytics:
    provider: google
    property: G-59FEKVM9G5
copyright: The older I get, the more I realize that most of life is a matter of what we pay attention to, of what we attend to [with focus].
repo_url: https://github.com/azusachino/harus-docs
edit_uri: edit/main/docs/
